"""Observer adapters that collect Nextflow execution events."""

from typing import Any

class WorkflowOutputCollector:
    """Collect workflow outputs, file publish events, and task workdirs.

    Example:
        >>> collector = WorkflowOutputCollector()
        >>> collector.workflow_events()
        []

    DEPENDS_ON:
    None

    EXTERNAL_DEPENDS_ON:
    logging
    """

    def __init__(self) -> None: ...
    def onFlowCreate(self, session: Any) -> None: ...
    def onFlowBegin(self) -> None: ...
    def onFlowComplete(self) -> None: ...
    def onProcessCreate(self, process: Any) -> None: ...
    def onProcessTerminate(self, process: Any) -> None: ...
    def onTaskPending(self, event: Any) -> None: ...
    def onTaskSubmit(self, event: Any) -> None: ...
    def onTaskStart(self, event: Any) -> None: ...
    def onTaskComplete(self, event: Any) -> None: ...
    def onTaskCached(self, event: Any) -> None: ...
    def onFlowError(self, event: Any) -> None: ...
    def onWorkflowOutput(self, event: Any) -> None: ...
    def onFilePublish(self, event: Any) -> None: ...
    def workflow_events(self) -> list[dict]: ...
    def file_events(self) -> list[dict]: ...
    def task_workdirs(self) -> list[str]: ...
def _record_task_workdir(self, event: Any, hook_name: str) -> None:
    """Record workdir from a task callback.

    Example:
        >>> _record_task_workdir(event, "onTaskComplete")

    DEPENDS_ON:
        None

        EXTERNAL_DEPENDS_ON:
        logging
        """
        ...
